# Spring Boot application settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportyshoesdb
    username: root
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Server settings
server:
  port: 8080
  servlet:
    context-path: /myapp

# Logging settings
logging:
  level:
    org.springframework: INFO
